AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'app/mailers/**/*'
    - 'app/jobs/**/*'
    - 'app/channels/**/*'
    - 'config.ru'
    - 'app/models/application_record.rb'
Style/RedundantReturn:
  Enabled: false
Style/Documentation:
  Enabled: true
  Exclude:
    - 'app/serializers/*'
    - 'app/controllers/*'
